### ISSUE TITLE
To-Do List

### ISSUE THREAD

**Issue by gelmutyansky** [gelmutyansky/HatPostingUWP#1]
### Задачи, связанные с загрузкой контента:
- [ ] Сделать загрузку видеозаписей из Reddit: разобраться, как соединять аудио и видео дорожки в приложении
- [ ] Сделать загрузку видеозаписей из Tumblr: дополнительных действий не требуется, только скачать
- [ ] Сделать загрузку GIF-анимаций

### Задачи, связанные с представлением контента:
- [ ] Адаптировать просмотрщик под видеозаписи: часть кода уже есть, но надо пересмотреть
- [ ] Сделать добавление хэштегов к описанию на основе выбранной группы: у групп свои списки хэштегов (например, #theowlhouse@funinnorefunds, #CoffeeShopAU@hatintime, итд)
- [ ] Заменить просмотр изображений и навигацию на ListView 
- [ ] После замены на ListView вернуть возможность скроллить приложение

### Задачи, связанные с выгрузкой контента в VK:
- [ ] Сделать выгрузку видеозаписей
- [ ] Сделать загрузку GIF: через документы?

### Трудные QoL задачи:
- [ ] Найти новое место для хранения чувствительной информации (ключи API, secret и проч)
- [ ] Обернуть опасные участки (работа с сетью и файловой системой) try-catch конструкциями и проверять, всё ли правильно выполнилось

### Недостижимые QoL идеи:
- [ ] Переделать приложение для использования сторонним пользователями со входом в свой аккаунт VK (хотя тут может потребоваться также вход в аккаунты Reddit и Tumblr)
- [ ] Переделать приложение под паттерн MVVM?
